[build]
  builder = "nixpacks"
  buildCommand = "npm install"

[deploy]
  startCommand = "node index.js"
  restartPolicyType = "on-failure"
  healthcheckPath = "/health"
  healthcheckTimeout = 30

[env]
  NODE_ENV = "production"